ValidationApplication/Pages/CreateBookUsingRazor.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ValidationApplication.Data;
using ValidationApplication.Models;
using ValidationApplication.Resources;
using ValidationApplication.Validations;

namespace ValidationApplication.Pages
{
    public class CreateBookUsingRazorModel : PageModel
    {
        private readonly BookDbContext _dbContext;

        public CreateBookUsingRazorModel(BookDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public List<SelectListItem> GenreCollection { get; } = new List<SelectListItem>
        {
            new SelectListItem { Value = "Fiction", Text = "Fiction" },
            new SelectListItem { Value = "Horror", Text = "Horror" },
            new SelectListItem { Value = "Fantasy", Text = "Fantasy" },
            new SelectListItem { Value = "Mystery", Text = "Mystery" },
            new SelectListItem { Value = "Scifi", Text = "Scifi" }
         };

        // This attribute maps properties of the Book model with the HTML form data.
        [BindProperty] 
        public RazorBookModel Book { get; set; } // The model used in the HTML form.

        [BindProperty]
        [Required]
        [ISBN]
        [PageRemote(HttpMethod = "post",
            AdditionalFields = "__RequestVerificationToken",
            PageHandler = "CheckISBN")]
        public string ISBN { get; set; }

        public void OnGet()
        {
            
        }

        // This method is called when the user submits the form.
        public async Task<IActionResult> OnPostBook()
        {
            // All properties of the Book model are filled.
            if (!ModelState.IsValid)
                return Page();

            _dbContext.Add(new Book()
            {
                ISBN = ISBN,
                Name = Book.Name,
                AuthorName = Book.AuthorName,
                Description = Book.Description,
                Email = Book.Email,
                Genres = Book.Genres,
                NumberOfPages = Book.NumberOfPages,
                Url = Book.Url,
            });
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("Success");
        }

        public JsonResult OnPostCheckISBN(string isbn)
        {
            var isbnAlreadyExists = _dbContext.Books.Any(x => x.ISBN == isbn);
            if (isbnAlreadyExists)
                return new JsonResult("The ISBN already exists");
            else
                return new JsonResult(true);
        }
    }
}

ValidationApplication/Pages/CreateObject.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ValidationApplication.Pages
{
    public class CreateObjectModel : PageModel
    {
        [BindProperty]
        public ObjectCreationInput Input { get; set; }

        public class ObjectCreationInput
        {
            [Required]
            public string SKU { get; set; }

            [Required]
            [StringLength(maximumLength: 10, MinimumLength = 4)]
            public string Name { get; set; }

            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Url]
            public string Url { get; set; }

            public string Zip { get; set; }

            public int NumberOfItems { get; set; }
        }

        public void OnGet()
        {
            
        }

        public async Task<IActionResult> OnPostObject()
        {
            if (ModelState.IsValid)
            {

            }
            return Page();
        }
    }
}

ValidationApplication/Pages/Success.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ValidationApplication.Pages
{
    public class SuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ValidationApplication/Pages/_ViewStart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ValidationApplication.Pages
{
    public class _ViewStartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ValidationApplication/Pages/CreateBook.cshtml
@page
@model ValidationApplication.Pages.CreateBookModel
@{
    ViewData["Title"] = "Razor Page Book Creation";
}

<div>Create book with validation using a <strong>Razor</strong> Page</div>

<form asp-page="/CreateBook" asp-page-handler="Book" method="post">
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label class="form-label">ISBN (example 978-3-16-148410-0)</label>
        <input asp-for="ISBN" class="form-control">
        <span asp-validation-for="ISBN"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Name</label>
        <input asp-for="Book.Name" class="form-control">
        <span asp-validation-for="Book.Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Author's Name</label>
        <input asp-for="Book.AuthorName" class="form-control">
        <span asp-validation-for="Book.AuthorName"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input asp-for="Book.Email" class="form-control">
        <span asp-validation-for="Book.Email"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Confirm Email</label>
        <input asp-for="Book.EmailRepeated" class="form-control">
        <span asp-validation-for="Book.EmailRepeated"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input asp-for="Book.Description" class="form-control">
        <span asp-validation-for="Book.Description"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Url</label>
        <input asp-for="Book.Url" class="form-control">
        <span asp-validation-for="Book.Url"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">NumberOfReaders</label>
        <input asp-for="Book.NumberOfPages" class="form-control">
        <span asp-validation-for="Book.NumberOfPages"></span>
    </div>
    <button type="submit" class="btn btn-primary" asp-page="/CreateBook" asp-page-handler="Book">Submit</button>
</form>

ValidationApplication/Pages/CreateBookUsingRazor.cshtml
@page
@model ValidationApplication.Pages.CreateBookUsingRazorModel
@{
    ViewData["Title"] = "Razor Page Book Creation";
}

<div>Create book with validation using a <strong>Razor</strong> Page</div>

<form asp-page="/CreateBookUsingRazor" asp-page-handler="Book" method="post">
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label class="form-label">ISBN (example 978-3-16-148410-0)</label>
        <input asp-for="ISBN" class="form-control">
        <span asp-validation-for="ISBN"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Name</label>
        <input asp-for="Book.Name" class="form-control">
        <span asp-validation-for="Book.Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Author's Name</label>
        <input asp-for="Book.AuthorName" class="form-control">
        <span asp-validation-for="Book.AuthorName"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input asp-for="Book.Email" class="form-control">
        <span asp-validation-for="Book.Email"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Confirm Email</label>
        <input asp-for="Book.EmailRepeated" class="form-control">
        <span asp-validation-for="Book.EmailRepeated"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        <input asp-for="Book.Description" class="form-control">
        <span asp-validation-for="Book.Description"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Genres</label>
        <select asp-for="Book.Genres" asp-items="Model.GenreCollection" class="form-control"></select>
        <span asp-validation-for="Book.Genres"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Url</label>
        <input asp-for="Book.Url" class="form-control">
        <span asp-validation-for="Book.Url"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">NumberOfReaders</label>
        <input asp-for="Book.NumberOfPages" class="form-control">
        <span asp-validation-for="Book.NumberOfPages"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ValidationApplication/Pages/CreateObject.cshtml
@page
@model ValidationApplication.Pages.CreateObjectModel
@{
}
<form asp-page="/CreateObject" asp-page-handler="Object" method="post">
    <div class="mb-3">
        <label class="form-label">SKU</label>
        <input asp-for="Input.SKU" class="form-control">
        <span asp-validation-for="Input.SKU"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Name</label>
        <input asp-for="Input.Name" class="form-control">
        <span asp-validation-for="Input.Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input asp-for="Input.Email" class="form-control">
        <span asp-validation-for="Input.Email"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Url</label>
        <input asp-for="Input.Url" class="form-control">
        <span asp-validation-for="Input.Url"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Zip</label>
        <input asp-for="Input.Zip" class="form-control">
        <span asp-validation-for="Input.Zip"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">NumberOfItems</label>
        <input asp-for="Input.NumberOfItems" class="form-control">
        <span asp-validation-for="Input.NumberOfItems"></span>
    </div>
    <button type="submit" class="btn btn-primary" asp-page="/CreateObject" asp-page-handler="Object">Submit</button>
</form>

ValidationApplication/Pages/Success.cshtml
@page
@model ValidationApplication.Pages.SuccessModel
@{
}
congratulations! The book created succesfully